[supervisord]
  nodaemon=true

  [program:snmpd]
  command=snmpd -f -Lo -C -c /etc/snmp/snmpd.conf
  autostart=true
  autorestart=true

  [program:backend]
  command=java -jar /app/backend/target/app-0.0.1-SNAPSHOT.jar
  autostart=true
  autorestart=true

  [program:frontend]
  command=npm run dev --prefix /app/frontend
  autostart=true
  autorestart=true
